export type Rule = {
  id: string;
  ruleId: string;
  name: string;
  createdDate: string;
  description: string;
  conditions: string;
  gatewayRouting: string;
  active: boolean;
};

export const initialRules: Rule[] = [
  {
    id: "1",
    ruleId: "id-dll-ll1",
    name: "Rule Example 1",
    createdDate: "Apr 23, 2025 9:18 am",
    description: "This is a descriptor field. Is not intended to be mandatory.",
    conditions: "Any type of payment",
    gatewayRouting: "Default route through SQUARE-AU-005, if fails try with STRIPE-EU-005, if fails try with ADYEN-UK-005",
    active: true,
  },
  {
    id: "2",
    ruleId: "id-dll-ll2",
    name: "Rule Example 2",
    createdDate: "Apr 21, 2025 9:55 pm",
    description: "Routes high-value transactions through preferred gateway.",
    conditions: "Amount greater than $500",
    gatewayRouting: "Default route through STRIPE-EU-005, if fails try with ADYEN-UK-005",
    active: true,
  },
  {
    id: "3",
    ruleId: "id-dll-ll3",
    name: "Rule Example 3",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Routes EU transactions through EU gateways for compliance.",
    conditions: "Country is in EU region",
    gatewayRouting: "Default route through ADYEN-UK-005, if fails try with STRIPE-EU-005",
    active: true,
  },
  {
    id: "4",
    ruleId: "id-dll-ll4",
    name: "Rule Example 4",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Handles recurring subscription payments.",
    conditions: "Payment type is Subscription",
    gatewayRouting: "Default route through BRAINTREE-US-001",
    active: true,
  },
  {
    id: "5",
    ruleId: "id-dll-ll5",
    name: "Rule Example 5",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Routes ACH payments to ACH-capable gateways.",
    conditions: "Payment method is ACH",
    gatewayRouting: "Default route through GOCARD-US-003",
    active: true,
  },
  {
    id: "6",
    ruleId: "id-dll-ll6",
    name: "Rule Example 6",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Handles SEPA direct debit payments.",
    conditions: "Payment method is SEPA",
    gatewayRouting: "Default route through BRAINTREE-EU-002",
    active: true,
  },
  {
    id: "7",
    ruleId: "id-dll-ll7",
    name: "Rule Example 7",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Routes mobile wallet payments.",
    conditions: "Payment method is Apple Pay or Google Pay",
    gatewayRouting: "Default route through STRIPE-US-004, if fails try with ADYEN-US-006",
    active: true,
  },
  {
    id: "8",
    ruleId: "id-dll-ll8",
    name: "Rule Example 8",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Handles trial period payment processing.",
    conditions: "Subscription is in trial period",
    gatewayRouting: "Default route through SQUARE-AU-005",
    active: true,
  },
  {
    id: "9",
    ruleId: "id-dll-ll9",
    name: "Rule Example 9",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Routes retry attempts through backup gateways.",
    conditions: "Payment attempt number is greater than 1",
    gatewayRouting: "Default route through ADYEN-UK-005, if fails try with BRAINTREE-US-001",
    active: true,
  },
  {
    id: "10",
    ruleId: "id-dll-ll10",
    name: "Rule Example 10",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Catch-all rule for unmatched payment types.",
    conditions: "All payments",
    gatewayRouting: "Default route through STRIPE-EU-005",
    active: true,
  },
  {
    id: "11",
    ruleId: "id-dll-ll1",
    name: "Rule Example 1 (Inactive)",
    createdDate: "Apr 23, 2025 9:18 am",
    description: "Disabled version of the primary rule.",
    conditions: "Any type of payment",
    gatewayRouting: "Default route through SQUARE-AU-005",
    active: false,
  },
  {
    id: "12",
    ruleId: "id-dll-ll2",
    name: "Rule Example 2 (Inactive)",
    createdDate: "Apr 21, 2025 9:55 pm",
    description: "Disabled high-value routing rule.",
    conditions: "Amount greater than $500",
    gatewayRouting: "Default route through STRIPE-EU-005",
    active: false,
  },
  {
    id: "13",
    ruleId: "id-dll-ll3",
    name: "Rule Example 3 (Inactive)",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Disabled EU compliance rule.",
    conditions: "Country is in EU region",
    gatewayRouting: "Default route through ADYEN-UK-005",
    active: false,
  },
  {
    id: "14",
    ruleId: "id-dll-ll4",
    name: "Rule Example 4 (Inactive)",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Disabled subscription routing.",
    conditions: "Payment type is Subscription",
    gatewayRouting: "Default route through BRAINTREE-US-001",
    active: false,
  },
  {
    id: "15",
    ruleId: "id-dll-ll5",
    name: "Rule Example 5 (Inactive)",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Disabled ACH routing.",
    conditions: "Payment method is ACH",
    gatewayRouting: "Default route through GOCARD-US-003",
    active: false,
  },
  {
    id: "16",
    ruleId: "id-dll-ll6",
    name: "Rule Example 6 (Inactive)",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Disabled SEPA routing rule.",
    conditions: "Payment method is SEPA",
    gatewayRouting: "Default route through BRAINTREE-EU-002",
    active: false,
  },
  {
    id: "17",
    ruleId: "id-dll-ll7",
    name: "Rule Example 7 (Inactive)",
    createdDate: "Apr 29, 2025 8:45 pm",
    description: "Disabled mobile wallet routing.",
    conditions: "Payment method is Apple Pay or Google Pay",
    gatewayRouting: "Default route through STRIPE-US-004",
    active: false,
  },
];
